config:
  email: null
  accept-agreement: false
  agreement: https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf
  registrationUrl: null
  production: false
  ca: letsencrypt
  enableServerWide: true
  serverCertificateMD5: null
  additional:
    country: null
    state: null
    city: null
    organization: null
domains: [
  ]
certificates: [
  ]