# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: ./gradlew clean writePropertiesFile shadowJar :TemplatesPlugin:build javadocArchive sourcesArchive writeNewPom

#after_success:
  # Check if commit is not a pull request, if repo is official, and branch is master, generate and deploy artifacts and reports
  #- "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == GlowstoneMC/Glowstone ]] && [[ $TRAVIS_BRANCH == master ]] && ./gradlew publish"

# Notification services
# notifications
  # Disable build status email notifications, until the issue with forks is fixed
  # email false
  # webhooks
    # Send build information and status to Notifico
    #- http://n.tkte.ch/h/1918/S53Phouna3jUVXcxFc3VjQ83

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
 
