# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: ./gradlew clean writePropertiesFile shadowJar :TemplatesPlugin:build javadocArchive sourcesArchive writeNewPom

#after_success:
#  # Check if commit is not a pull request, if repo is official, and branch is master, generate and deploy artifacts and reports
#  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == ChioriGreene/ChioriWebServer ]] && [[ $TRAVIS_BRANCH == v9-experimental ]] && gradle publish"

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
 
