name: Chiori-chan Template Plugin
author: Chiori Greene
main: com.chiorichan.plugin.builtin.template.Template
version: '1.1'
depends: []

commands:
     status:
          description: Framework Status
          usage: /status
