name: Chiori Framework
author: Chiori Greene
main: com.chiorichan.plugin.builtin.Template
version: '1.0'
depends: []

commands:
     status:
          description: Framework Status
          usage: /status
