server:
  httpHost: ''
  httpPort: 8080
  httpsPort: 0
  httpsKeystore: server.keystore
  httpsSecret: abcd1234
  tcpHost: ''
  tcpPort: 1024
  queryEnabled: false
  queryHost: ''
  queryPort: 8992
  queryUseColor: true
  admin: chiorigreene@gmail.com
  allowDirectoryListing: false
  haltOnSevereError: false
  throwInternalServerErrorOnWarnings: false
  enableWebServer: true
  enableTcpServer: true
  allowQuery: false
  installationUID: null
  disableTracking: false
  defaultTextEncoding: UTF-8
  defaultBinaryEncoding: ISO-8859-1
  developmentMode: false
  maxFileUploadKb: 5120
  tmpFileDirectory: tmp
  webFileDirectory: webroot
  fileUploadMinInMemory: 0
  database:
    database: chiorifw
    type: sqlite
    host: localhost
    port: 3306
    username: fwuser
    password: fwpass
    dbfile: server.db
plugins:
  useTimings: true
permissions:
  backend: file
  file: permissions.yaml
  debug: false
  allowOps: true
  preloadGroups: true
  preloadEntities: true
settings:
  update-folder: update
  deprecated-verbose: default
  shutdown-message: Server Shutdown
  whitelist: false
console:
  color: true
  style: '&r&7[&d%ct&7] %dt %tm [%lv&7]&f'
  dateFormat: MM-dd
  timeFormat: HH:mm:ss.SSS
  hideLoggerName: false
  developerMode: true
auto-updater:
  enabled: true
  on-broken:
  - warn-console
  - warn-ops
  on-update:
  - warn-console
  - warn-ops
  preferred-channel: rb
  host: jenkins.chiorichan.com
  suggest-channels: true
  check-interval: 30
  console-only: true
sessions:
  defaultCookieName: SessionId
  defaultTimeout: 3600
  defaultTimeoutWithLogin: 86400
  defaultTimeoutRememberMe: 604800
  allowNoTimeoutPermission: false
  rearmTimeoutWithEachRequest: true
  reuseVacantSessions: true
  maxSessionsPerIP: 6
  allowIPChange: false
  cleanupInterval: 5
  datastore: file
  debug: false
accounts:
  allowLoginTokens: true
  singleLogin: false
  singleLoginMessage: You logged in from another location.
  debug: false
  sqlType:
    enabled: false
    default: false
    table: accounts
    fields:
      - username
      - email
      - phone
  fileType:
    enabled: true
    default: true
    filebase: accounts
    fields:
      - username
      - email
      - phone
framework:
  sites:
    defaultTitle: Unnamed Site
    autoCreateSubdomains: true
    subdomainsDefaultToRoot: false
    defaultSite: ''
advanced:
  processors:
    imageProcessorEnabled: true
    useFastGraphics: false
    minifierJSProcessorEnabled: true
    lessProcessorEnabled: true
    coffeeProcessorEnabled: true
  interpreters:
    gspEnabled: true
    groovyEnabled: true
  security:
    unmodifiableMapsEnabled: true
    requestMapEnabled: true
    defaultScriptTimeout: 30
  libraries:
    libPath: libraries