server:
  httpHost: ''
  httpPort: 8080
  httpsPort: 4443
  tcpHost: ''
  tcpPort: 1024
  admin: chiorigreene@gmail.com
  allowDirectoryListing: false
  haltOnSevereError: false
  enableWebServer: true
  enableTcpServer: true
  allowQuery: false
  installationUID: null
  defaultEncoding: UTF-8
  defaultImageEncoding: ISO-8859-1
  developmentMode: true
  maxFileUploadKb: 5120
  tmpFileDirectory: tmp
  database:
    database: chiorifw
    type: none
    host: localhost
    port: 3306
    username: fwuser
    password: fwpass
    dbfile: chiori.db
settings:
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server Shutdown
  whitelist: false
  webroot: webroot
auto-updater:
  enabled: true
  on-broken:
  - warn-console
  - warn-ops
  on-update:
  - warn-console
  - warn-ops
  preferred-channel: rb
  host: jenkins.chiorichan.com
  suggest-channels: true
  check-interval: 30
  console-only: true
sessions:
  defaultSessionName: sessionId
  defaultTimeout: 3600
  defaultTimeoutWithLogin: 86400
  defaultTimeoutRememberMe: 604800
  allowNoTimeoutPermission: false
  rearmTimeoutWithEachRequest: true
  reuseVacantSessions: true
  maxSessionsPerIP: 6
  allowIPChange: false
  cleanupInterval: 5
  adapterType: none
accounts:
  maxLogins: -1
  lookupAdapter:
    type: none
    table: ''
    fields: {}
  operators:
  - noLogin
framework:
  sites:
    defaultTitle: Unnamed Site
    autoCreateSubdomains: true
    subdomainsDefaultToRoot: false
    defaultSite: ''
advanced:
  processors:
    imageProcessorEnabled: true
    useFastGraphics: false
    minifierJSProcessorEnabled: true
    lessProcessorEnabled: true
    coffeeProcessorEnabled: true
  interpreters:
    gspEnabled: true
    groovyEnabled: true
  security:
    requestMapEnabled: true