name: Interactive Console Plugin
author: Chiori Greene
main: com.chiorichan.plugin.console.ConsolePlugin
version: '1.0'
depends: []
natives:
  linux-x86_64: natives/linux-x86_64/libjcurses.so
  linux-x86: natives/linux-x86/libjcurses.so
libraries:
  - "com.baulsupp.kolja:jcurses:0.9.5.3"
gitHubBaseUrl: https://raw.githubusercontent.com/ChioriGreene/ChioriWebServer/master/InteractiveConsolePlugin/src/main/java/