name: ZXing Plugin
author: Chiori Greene
main: com.chiorichan.plugin.zxing.ZxingPlugin
version: '1.0'
depends: []
libraries:
  - "com.google.zxing:core:3.1.0"
  - "com.google.zxing:javase:3.1.0"
gitHubBaseUrl: https://raw.githubusercontent.com/ChioriGreene/ChioriWebServer/master/ZXingPlugin/src/main/java/