name: SSH Console Plugin
author: Chiori Greene
main: com.chiorichan.plugin.sshd.SSHPlugin
version: '1.0'
depends: []
libraries:
  - "org.apache.sshd:sshd:1.3.0"
gitHubBaseUrl: https://raw.githubusercontent.com/ChioriGreene/ChioriWebServer/master/SSHConsolePlugin/src/main/java/
