name: Email Plugin
author: Chiori Greene
main: com.chiorichan.plugin.email.EmailPlugin
version: '1.0'
depends: []
libraries:
  - "javax:javaee-api:7.0"
gitHubBaseUrl: https://raw.githubusercontent.com/ChioriGreene/ChioriWebServer/master/EmailPlugin/src/main/java/