name: Dropbox Plugin
author: Chiori Greene
main: com.chiorichan.plugin.dropbox.Dropbox
version: '1.0'
depends: []
libraries:
  - "com.dropbox.core:dropbox-core-sdk:1.7.7"
  - "com.fasterxml.jackson.core:jackson-core:2.4.0"